from mixins.projectUrls import *

# separating roles for each urls

PUJA_PUBLIC_URLS = []

ANONYMOUS_USER_WHITELIST = [
    DISTRICT_SEARCH_LIST,
    ADMIN_USER_LOGIN_CREATE,
    CUSTOMER_USER_LOGIN_CREATE,
    REGISTER_CREATE,
    REGISTER_PATCH,
    DISTRICT_SEARCH_LIST,
    LOGIN_REFRESH_POST,
    MONASTERIES_LIST,
    MONASTERIES_READ,
    PUJAS_LIST,
    PUJAS_READ,
    VERIFY_OTP_POST,
    RESET_PASSWORD_CREATE,
    FORGOT_PASSWORD_POST,
    BANNERIMG_LIST,
    BANNERIMG_READ,
    MONASTERY_REGISTER,
    NCHL_PAYMENT_SUCCESS,
    NCHL_PAYMENT_FAILURE,
]


CUSTOMER_URLS = [
    BANNERIMG_LIST,
    BANNERIMG_READ,
    DISTRICT_SEARCH_LIST,
    PROFILE_LIST,
    PROFILE_READ,
    PROFILE_CREATE,
    PROFILE_PATCH,
    CHANGE_PASSWORD_CREATE,
    MONASTERIES_LIST,
    PUJAS_LIST,
    PUJAS_READ,
    PUJAREQUESTS_LIST,
    PUJAREQUESTS_READ,
    PUJAREQUESTS_CREATE,
    USER_NOTIFICATIION_LIST,
    USER_NOTIFICATIION_READ,
    USER_NOTIFICATIION_MARK_AS_READ,
    USER_NOTIFICATIION_LIST_READ,
    FCM_DEVICE_REGISTER_CREATE,
    NABIL_PAYMENT_INITIATE,
    VERIFY_ESEWA_PAYMENT_POST,
    VERIFY_KHALTI_PAYMENT_POST,
    ON_NABIL_PAYMENT_SUCCESS,
    NCHL_PAYMENT_INITIATE,
    PUJA_TWEAK_CREATE,
]


ADMIN_URLS = [
    CUSTOMER_URLS,
    PROFILE_DELETE,
    MONASTERIES_LIST,
    MONASTERIES_READ,
    PUJAS_CREATE,
    PUJAS_UPDATE,
    PUJAS_PATCH,
    PUJAS_DELETE,
    FINANCELOGS_LIST,
    FINANCELOGS_READ,
    PUJAREQUESTS_UPDATE_PATCH,
    GENERATEPDFS_LIST,
    GENERATEPDFS_CREATE,
    UPDATE_MONASTERY,
]


SUPER_ADMIN_URLS = [
    BANNERIMG_CREATE,
    BANNERIMG_UPDATE,
    BANNERIMG_PATCH,
    BANNERIMG_DELETE,
    CUSTOMER_URLS,
    ADMIN_URLS,
    MONASTERIES_CREATE,
    MONASTERIES_UPDATE,
    MONASTERIES_PATCH,
    MONASTERIES_DELETE,
    PUJAREQUESTS_UPDATE,
    PUJAREQUESTS_PATCH,
    PUJAREQUESTS_DELETE,
    PUJAREQUESTS_POST,
    FINANCELOGS_CREATE,
    FINANCELOGS_UPDATE,
    FINANCELOGS_PATCH,
    FINANCELOGS_DELETE,
]


permission_map = {
    "SuperAdmin": SUPER_ADMIN_URLS,
    "Admin": ADMIN_URLS,
    "Customer": CUSTOMER_URLS,
}


class PermissionManager:
    """Permission manager"""

    def __init__(self) -> None:
        self.permission_map = permission_map

    def get_permission_map(self):
        """Provide role permission map."""
        return permission_map
