# Generated by Django 5.0.2 on 2024-02-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('district', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/images')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_time', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='problem_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.addcategory')),
            ],
        ),
        migrations.CreateModel(
            name='createBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_problem', models.CharField(max_length=36)),
                ('selected_brand', models.CharField(max_length=255)),
                ('booked_date', models.DateTimeField()),
                ('item_count', models.PositiveIntegerField()),
                ('time_period', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('problem_interval', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('appoint', 'appoint'), ('completed', 'completed'), ('onwork', 'onwork'), ('pending', 'pending')], max_length=20)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register')),
            ],
        ),
        migrations.AddField(
            model_name='addcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register'),
        ),
    ]
