# Generated by Django 4.2.6 on 2024-02-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_password_login_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcategory',
            name='user',
        ),
    ]
