# Generated by Django 4.2.6 on 2024-02-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_addcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.login'),
            preserve_default=False,
        ),
    ]
