# Generated by Django 4.2.6 on 2024-03-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
