# Generated by Django 4.2.6 on 2024-02-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_addcategory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcategory',
            old_name='user',
            new_name='register_id',
        ),
    ]
