# Generated by Django 4.2.6 on 2024-02-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_addcategory_register_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcategory',
            old_name='register_id',
            new_name='user',
        ),
    ]
