# Generated by Django 4.2.6 on 2024-04-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='price',
        ),
    ]
