# Generated by Django 4.2.6 on 2024-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_register_id_addcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='price',
            field=models.TextField(),
        ),
    ]
