# Generated by Django 4.2.6 on 2024-04-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_problem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooking',
            name='phone_number',
            field=models.TextField(default='0', max_length=12),
        ),
    ]
