# Generated by Django 4.2.6 on 2024-03-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_problem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbooking',
            name='problem',
        ),
        migrations.AlterField(
            model_name='createbooking',
            name='booked_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.problem'),
        ),
        migrations.AlterField(
            model_name='createbooking',
            name='status',
            field=models.CharField(choices=[('appoint', 'appoint'), ('completed', 'completed'), ('onwork', 'onwork'), ('pending', 'pending')], default='appoint', max_length=20),
        ),
    ]
