# Generated by Django 4.2.6 on 2024-03-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_createbooking_booked_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.register'),
        ),
    ]
