# Generated by Django 4.2.6 on 2024-03-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_createbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problem_images/'),
        ),
    ]
