# Generated by Django 4.2.6 on 2024-06-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_is_admin_user_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcategory',
            name='user',
        ),
    ]
