# Generated by Django 4.2.6 on 2024-06-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_addcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbooking',
            name='user',
        ),
    ]
