# Generated by Django 4.2.6 on 2024-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_createbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
