# Generated by Django 4.2.6 on 2024-06-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_createbooking_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='est_time',
        ),
    ]
